Implement InlineChoiceInteraction #11
riiid/qtikit pull request #19
Opened 2021-11-15 06:24 UTC by ragingwind

#11

2021-11-15 07:21 UTC, disjukr commented on packages/react/src/components/index.ts
> +}
실제로 하는 동작은 재귀적으로 xml namespace를 지운 문자열을 반환하는 것이니 `getOuterXmlWithoutNs` 같은 느낌으로 이름지으면 좋을거 같아요

2021-11-15 22:21 UTC, ragingwind commented on packages/react/src/components/index.ts
> +}
Good naming

2021-11-16 01:33 UTC, disjukr commented on packages/react/src/components/InlineChoice.tsx
> +import {InlineChoiceCharacteristics as InlineChoiceProps} from '@qtikit/model/src/qti2_2';
```suggestion
import {InlineChoiceCharacteristics as InlineChoiceProps} from '@qtikit/model/lib/qti2_2';
```

2021-11-16 01:33 UTC, disjukr commented on packages/react/src/interactions/ChoiceInteraction/ChoiceInteraction.tsx
> +import {ChoiceInteractionCharacteristics as ChoiceInteractionProps} from '@qtikit/model/src/qti2_2';
```suggestion
import {ChoiceInteractionCharacteristics as ChoiceInteractionProps} from '@qtikit/model/lib/qti2_2';
```

2021-11-16 01:33 UTC, disjukr commented on packages/react/src/interactions/ExtendedTextInteraction/ExtendedTextInteraction.tsx
> +import {ExtendedTextInteractionCharacteristics as ExtendedTextInteractionProps} from '@qtikit/model/src/qti2_2';
```suggestion
import {ExtendedTextInteractionCharacteristics as ExtendedTextInteractionProps} from '@qtikit/model/lib/qti2_2';
```

2021-11-16 01:52 UTC, Il9 requested changes

2021-11-16 01:52 UTC, Il9 commented on packages/react/src/components/InlineChoice.tsx
> +  return React.Children.map(children, child => child)?.join('') || '';
What is this map for?
Have you ever wanted a filter?

2021-11-16 01:52 UTC, Il9 commented on packages/react/src/components/Mathjax.tsx
> +const Mathjax: React.FC<MathjaxProps | any> = ({mathHtml, ...props}) => {
It seems to be an unnecessary any

2021-11-16 01:52 UTC, Il9 commented on packages/react/src/interactions/InlineChoiceInteraction/InlineChoiceInteraction.tsx
> +  const handleChange = (event: {target: {value: any}}) => {
```suggestion
  const handleChange: React.ChangeEventHandler = event => {
```
How about this?

2021-11-16 01:52 UTC, Il9 commented on packages/react/src/interactions/InlineChoiceInteraction/InlineChoiceInteraction.tsx
> +  const [value, setValue] = React.useState('$choose');
Wouldn't a placeholder value be null?

2021-11-16 01:52 UTC, Il9 commented on packages/react/src/qti.ts
> +import {isElementNode, isRootElement, isTextNode, isMathElement} from './utils/node';
👍

2021-11-16 01:52 UTC, Il9 commented on packages/react/src/utils/node.ts
> +type NodeType = typeof NodeType[keyof typeof NodeType];
How about splitting it into types?
types/node ?

2021-11-16 02:37 UTC, ragingwind commented on packages/react/src/utils/node.ts
> +type NodeType = typeof NodeType[keyof typeof NodeType];
After merge, at the cleaning time

2021-11-16 02:38 UTC, Il9 commented on packages/react/src/utils/node.ts
> +type NodeType = typeof NodeType[keyof typeof NodeType];
ok

2021-11-16 02:39 UTC, ragingwind commented on packages/react/src/interactions/InlineChoiceInteraction/InlineChoiceInteraction.tsx
> +  const [value, setValue] = React.useState('$choose');
No, $choose value make the first option item to be a default

2021-11-16 02:45 UTC, ragingwind commented on packages/react/src/components/InlineChoice.tsx
> +  return React.Children.map(children, child => child)?.join('') || '';
Sometime, children has N child. It would be needed to make a line HTML before inserting an <option>

afaik, we cannot use filter directly of children? Any suggestion?

2021-11-16 02:49 UTC, Il9 commented on packages/react/src/interactions/InlineChoiceInteraction/InlineChoiceInteraction.tsx
> +  const [value, setValue] = React.useState('$choose');
I know that,
that means How about setting the value of the first option to null?

2021-11-16 02:52 UTC, Il9 commented on packages/react/src/components/InlineChoice.tsx
> +  return React.Children.map(children, child => child)?.join('') || '';
Oh, my mistake.
I thought it was Array.map.

2021-11-16 03:50 UTC, ragingwind commented on packages/react/src/interactions/InlineChoiceInteraction/InlineChoiceInteraction.tsx
> +  const [value, setValue] = React.useState('$choose');
Like this? (value attr doesn't accept null)

```suggestion
  const [value, setValue] = React.useState<string | undefined>(undefined);
  
  return (
    <select value={value} onChange={handleChange}>
      <option>Choose...</option>
      {props.children}
    </select>
  );
```

2021-11-16 03:53 UTC, ragingwind commented on packages/react/src/interactions/InlineChoiceInteraction/InlineChoiceInteraction.tsx
> +  const handleChange = (event: {target: {value: any}}) => {
destructuring is not default?

2021-11-16 04:48 UTC, Il9 approved these changes

2021-11-16 04:48 UTC, merged