Implement MatchInteraction
riiid/qtikit pull request #40
Opened 2021-11-29 06:57 UTC by ragingwind

- Added `validate` hook while decoding
- Added MatchIteraction

2021-11-29 07:55 UTC, Il9 commented on packages/react/src/interactions/MatchInteraction/MatchInteraction.tsx
> +import CheckBox from 'src/components/CheckBox';
Please use relative path

2021-11-29 07:55 UTC, Il9 commented on packages/react/src/interactions/InteractionState.tsx
> +      [inputState, decode, validate, onChange, responseIdentifier]
I think validate should be a function that returns a boolean.
If new state pass validate then update to new state, else not update anything.
So prevInteractionState seems unnecessary.

2021-11-29 07:55 UTC, Il9 commented on packages/react/src/interactions/MatchInteraction/MatchInteraction.tsx
> +    },
MatchValidator only checks that newInteractionState exceeds max, so it should not return State.

2021-11-29 23:09 UTC, ragingwind commented on packages/react/src/interactions/MatchInteraction/MatchInteraction.tsx
> +import CheckBox from 'src/components/CheckBox';
Do you know how make vscode use relative path instead of this? It was added by vscode

2021-11-29 23:33 UTC, ragingwind commented on packages/react/src/interactions/InteractionState.tsx
> +      [inputState, decode, validate, onChange, responseIdentifier]
My suggestion is to make it like a reducer. However, the side calling `setInteractionState` on the last component/control sends already merged state. So you have a chance to manage/handle the new state before merging. How about this:

- The client only sends the new state using setInteractionState.
- setInteractionState call the decoder with the current state and the new state from the client
- The interaction decoder, decide whether to merge state or not

2021-11-30 00:25 UTC, ragingwind commented on packages/react/src/interactions/InteractionState.tsx
> +      [inputState, decode, validate, onChange, responseIdentifier]
// CheckBox.ts
```
const handleChange = () => {
    // only send new state
    setInteractionState({
      [indentifier]: !(interactionState[indentifier] === true),
    });
  };
```

// Interaction.ts
```
const [interactionState, setInteractionState] = useInteractionState({
    responseIdentifier,
    encode: userInput =>
      userInput.reduce((interactionState, identifier) => ({...interactionState, [identifier]: true}), {}),
    decode: (actions, state) => {
      const action = Object.entries(actions)[0];
      const [rowIdentifier, colIdentifier] = action[0].split(' ');
      const check = (action[1] === true ? matchSet.check : matchSet.uncheck).bind(matchSet);
      const reduce = (state: {[x: string]: unknown}) => Object.keys(state).filter(identifier => state[identifier]);

      // merge, reduce states by conditions
      return reduce({
        ...state,
        ...(check(rowIdentifier, colIdentifier) ? actions : {}),
      });
    },
  });
```

2021-11-30 03:34 UTC, Il9 requested changes

2021-11-30 03:34 UTC, Il9 commented on packages/react/src/components/CheckBox.tsx
> +const CheckBox: React.FC<CheckBoxProps> = ({indentifier}) => {
Isn't the name Checkbox correct?

2021-11-30 03:34 UTC, Il9 commented on packages/react/src/interactions/InteractionState.tsx
> +        }
onChange should be executed even without shouldUpdate

2021-11-30 03:34 UTC, Il9 commented on packages/react/src/interactions/InteractionState.tsx
> +  setInteractionState: (newInteractionState: InteractionState, prevInteractionState?: InteractionState) => void;
```suggestion
  setInteractionState: (newInteractionState: InteractionState) => void;
```

2021-11-30 03:34 UTC, Il9 commented on packages/react/src/interactions/InteractionState.tsx
> +        }
```suggestion
        if (!shouldUpdate || shouldUpdate(newInteractionState)) {
          onChange({
            ...inputState,
            [responseIdentifier]: decode(newInteractionState),
          });
        }
```

2021-11-30 03:34 UTC, Il9 commented on packages/react/src/interactions/MatchInteraction/MatchInteraction.tsx
> +      )[0];
It seems difficult to know what 0 and 1 of the entry are.

2021-11-30 03:34 UTC, Il9 commented on packages/react/src/interactions/MatchInteraction/MatchInteraction.tsx
> +      )[0];
How about this?
x, y are temp naming

```suggestion
      const [choice, checked] = next.filter(([x, y])=>
        current.length < next.length ? !interactionState[x] : y !== interactionState[x]
      )[0];
```

2021-11-30 03:34 UTC, Il9 commented on packages/react/src/interactions/MatchInteraction/MatchInteraction.tsx
> +      )[0];
And is there any case where there is no result of filtering?

2021-11-30 03:41 UTC, Il9 requested changes

2021-11-30 03:41 UTC, Il9 commented on packages/react/src/interactions/MatchInteraction/MatchSet.ts
> +    const {row, col} = this.getChoice(rowIdentifier, colIdentifier);
Haven't you decided to avoid doing find every update?
How about using the table only for render and creating a hash map for the matched count?

2021-11-30 04:08 UTC, ragingwind commented on packages/react/src/interactions/InteractionState.tsx
> +  setInteractionState: (newInteractionState: InteractionState, prevInteractionState?: InteractionState) => void;
Fixed in another commit

2021-11-30 04:13 UTC, ragingwind commented on packages/react/src/interactions/MatchInteraction/MatchInteraction.tsx
> +      )[0];
'No result of filtering' must not be happened. If there are same states at there, should be fixed before called the func

2021-11-30 04:18 UTC, ragingwind commented on packages/react/src/interactions/MatchInteraction/MatchSet.ts
> +    const {row, col} = this.getChoice(rowIdentifier, colIdentifier);
Because of sample count is super low, There are no significant changes between reference accessing and searching

2021-11-30 04:25 UTC, ragingwind commented on packages/react/src/interactions/MatchInteraction/MatchSet.ts
> +    const {row, col} = this.getChoice(rowIdentifier, colIdentifier);
There are any possible for having table for every choice(cell) in MatchSet, we could save all of information to the table not only only in finding row/col. We can improve when we need to.

2021-11-30 04:29 UTC, Il9 commented on packages/react/src/interactions/MatchInteraction/MatchInteraction.tsx
> +      )[0];
It would be nice to be able to indicate what the key and value actually are.

2021-11-30 04:30 UTC, Il9 commented on packages/react/src/interactions/InteractionState.tsx
> +  setInteractionState: (newInteractionState: InteractionState, prevInteractionState?: InteractionState) => void;
another pr?

2021-11-30 05:21 UTC, ragingwind commented on packages/react/src/interactions/MatchInteraction/MatchInteraction.tsx
> +      )[0];
any suggestions? key/value better than x, y

2021-11-30 06:04 UTC, Il9 commented on packages/react/src/interactions/MatchInteraction/MatchInteraction.tsx
> +      )[0];
What are the actual values ​​of key and value?
I think you should do it with the name of that value.

2021-11-30 06:47 UTC, Il9 approved these changes

2021-11-30 06:49 UTC, merged