Add ExtendedTextInteraction
riiid/qtikit pull request #7
Opened 2021-11-11 07:08 UTC by ragingwind

ExtendedTextInteraction is added without validating. it will be added soon

2021-11-11 07:26 UTC, Il9 requested changes

2021-11-11 07:26 UTC, Il9 commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +  const onChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
Handler는 handle${target}(Change[Verb]) 형식으로 부탁드립니다

2021-11-11 07:26 UTC, Il9 commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +  const onChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
여기는 handleChange가 되겠네요

2021-11-11 07:26 UTC, Il9 commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +  };
고정 값들은 컴포넌트 밖에 놔두는게 좋을 것 같습니다

2021-11-11 07:26 UTC, Il9 commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +  };
style 관련한건 emotion같은거 필요없을까요?

2021-11-11 07:26 UTC, Il9 commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +  const onChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
변수명도 내부적으로 줄임말을 최대한 쓰지말자고 정해서
event로 해주시면 좋을 것 같습니다

2021-11-11 07:26 UTC, Il9 commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +          onChange={onChange}></textarea>
이 interation의 경우에는 이게 component로 분리가 되야 하는게 아닌가요?

2021-11-11 07:26 UTC, Il9 commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +  const {stringIdentifier, responseIdentifier} = props;
```suggestion
const ExtendedTextInteraction: React.FC<ExtendedTextInteractionProps | any> = ({stringIdentifier, responseIdentifier}) => {
```

이게 어떨까요

2021-11-11 07:26 UTC, Il9 commented on packages/react/src/stories/SimpleInteractions.stories.tsx
> +const getItemXmlUrl = (fileName: string) => `http://localhost:6006/tests/items/${fileName}`;
이건 util로 빠져야 될 것 같습니다

2021-11-11 07:26 UTC, Il9 commented on packages/react/src/stories/SimpleInteractions.stories.tsx
> +const getItemXmlUrl = (fileName: string) => `http://localhost:6006/tests/items/${fileName}`;
base url 은 constant로 정의해두는 것도 좋아 보입니다

2021-11-11 07:47 UTC, ragingwind commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +  };
스타일은 잘 모르겠어요.. 일단 하드코딩 늑김

2021-11-11 07:48 UTC, ragingwind commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +          onChange={onChange}></textarea>
잘 이해못했어요. Textarea?

2021-11-11 07:50 UTC, Il9 commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +          onChange={onChange}></textarea>
SimpleChoice 같이 Interaction 내부 form들은 component로 분리 되야 하는게 아닌가 하는 말이었씁니다

2021-11-11 07:53 UTC, ragingwind commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +          onChange={onChange}></textarea>
저게 xml 에 있는게 아니라서. 애매하네요. 내일 같이 봐요. 그리고 우리 영어로 해야..

2021-11-11 07:55 UTC, Il9 commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +          onChange={onChange}></textarea>
넵 내일 보시죠.
영어는 여긴 Riiid 레포라서 괜찮지않을까요?

2021-11-11 20:40 UTC, disjukr commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +  const onChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
(헉 몰랐던 맥락)

2021-11-11 22:19 UTC, ragingwind commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +  const onChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
onChange was my mistake.

2021-11-11 22:20 UTC, ragingwind commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +          onChange={onChange}></textarea>
I have no idea. I just thought that English is main lang for open source projects

2021-11-11 23:27 UTC, ragingwind commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +  const {stringIdentifier, responseIdentifier} = props;
destructed parameter is first-class?

2021-11-11 23:27 UTC, ragingwind commented on packages/react/src/stories/SimpleInteractions.stories.tsx
> +const getItemXmlUrl = (fileName: string) => `http://localhost:6006/tests/items/${fileName}`;
I changed the way of getting test xml.

2021-11-11 23:31 UTC, ragingwind commented on packages/react/src/interactions/ExtendedTextInteraction.tsx
> +  const {stringIdentifier, responseIdentifier} = props;
props needed at this below

2021-11-12 01:39 UTC, Il9 approved these changes

2021-11-12 01:39 UTC, merged